--- #YAML:1.0
 name: Finance-PremiumBonds
 abstract:  Check if Premium Bond holder's number has won a prize
 version: 0.02
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   WWW::Mechanize: 0
   perl: 5.005
 build_requires:
   Test::More: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand
